version: '3.8'
services:
  dev-db:
    image: postgres:alpine
    ports:
      - {{cookiecutter.db_port}}:5432
    environment:
      POSTGRES_USER: {{cookiecutter.postgres_user}}
      POSTGRES_PASSWORD: {{cookiecutter.postgres_password}}
      POSTGRES_DB: {{cookiecutter.db_name}}
    networks:
      - skindex
networks:
  skindex: